# Generated by Django 5.2.7 on 2025-10-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
